# -*- coding: utf-8 -*-
"""importSample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DXsE45_R-T_W9COKdP-zwlj2NWMriLjU
"""

def func01():
  print("This is function 01")

def func02():
  print("This is function 02")

def func03(intVar):
  tmpInt = intVar
  return tmpInt + 1